name: Compute matrix job

on: push

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      ci_matrix: ${{ steps.get-ci-matrix.outputs.result }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Get CI matrix"
        id: get-ci-matrix
        uses: actions/github-script@v3
        with:
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/get-ci-matrix.js`);
            return await script({ github, context, core, io });

  run_matrix:
    runs-on: windows-2019
    needs:
      - prepare
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.ci_matrix.matrix) }}

    steps:
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '>=12'
      - run: echo ${{ matrix.value }}
