name: Compute matrix job

on: push

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-ci-matrix.outputs.result }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Get CI matrix"
        id: get-ci-matrix
        uses: actions/github-script@v3
        with:
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/get-ci-matrix.js`);
            return await script({ github, context, core, io });

  run_matrix:
    runs-on: ubuntu-latest
    needs:
      - prepare
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}

    env:
      ACTION_TEST_SOME_SECRET: ${{ secrets.ACTION_TEST_SOME_SECRET }}

    steps:
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '>=12'
      - run: echo "${{ matrix.value }}"
      - run: echo "$ACTION_TEST_SOME_SECRET"
