name: Compute matrix job

on: push

jobs:
  get_list:
    runs-on: ubuntu-latest
    outputs:
      list: ${{ steps.get-list.result }}
    steps:
      - id: get-list
        uses: actions/github-script@v3
        with:
          result-encoding: string
          script: return '["a", "b"]'

      - run: echo ${{ steps.get-list.result }}

  use_list:
    runs-on: ubuntu-latest
    needs:
      - get_list
    strategy:
      matrix:
        value: ${{ fromJSON(needs.get_list.outputs.list) }}

    steps:
      - run: "echo value: ${{ matrix.value }}"
