name: Compute matrix job

on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Job to do'
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-ci-matrix.outputs.result }}
      run_matrix_needs: ${{ steps.get-ci-matrix.outputs.run_matrix_needs }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Get CI matrix"
        id: get-ci-matrix
        uses: actions/github-script@v3
        with:
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/get-ci-matrix.js`);
            return await script({ github, context, core, io });

  dependency:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo hi!

  run_matrix:
    runs-on: ubuntu-latest
    needs:
      - prepare
      - dependency

    if: always()
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}

    env: ${{ fromJSON(secrets.ACTION_TEST_JSON_SECRETS) }}

    steps:
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '>=12'

      - run: echo "${{ matrix.value }}"
      - run: echo "$ACTION_TEST_SOME_SECRET $ACTION_TEST_HIDDEN_SECRET"
        env:
          ACTION_TEST_HIDDEN_SECRET: ${{ secrets.ACTION_TEST_HIDDEN_SECRET }}
