name: Schedule

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: "Trigger CI"
        uses: actions/github-script@v3
        with:
          script: |
            await github.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
              owner: 'Dico200'
              repo: 'action-test',
              workflow_id: 'compute-matrix-job.yml',
              ref: 'master',
              inputs: {
                job: 'DO THE THING!'
              }
            })
